### ISSUE TITLE
are normal types still support?

### ISSUE THREAD

**Issue by Anda001** [daltonks/Unofficial-SignalR-Protobuf#1]
when use this lib,the type  int, string still support ? or have to change all the type to protobuf?

**Comment by daltonks** [comment]
Hello! Only protobuf models are supported. If you would like primitive-like support, you could create protobuf messages like `IntProto`, `StringProto` and create implicit/explicit operators in `partial` classes.

**Comment by Anda001** [comment]
I got it. tks.
